// Package entity of db entity
// Code generated by go-god/tbox. DO NOT EDIT!!!

package entity

// UserTable for user
const UserTable = "user"

// UserEntity for user table entity struct.
type UserEntity struct {
	ID	int64	`json:"id" gorm:"id primaryKey"`
	User	string	`json:"user" gorm:"user"`
	Name	string	`json:"name" gorm:"name"`
}
